name: XCUI Testing

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    strategy:
      matrix:
        config: ['13']
        include:
          - config: '13'
              runner: 'macos-13'
              xcode-path: '/Applications/Xcode_15.app/Contents/Developer'
              upload-name: 'build-logs-macos13'
    
    name: Build and Test Komet on macOS
    runs-on: ${{ matrix.runner }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build Release
        env:
          DEVELOPER_DIR: ${{ matrix.xcode-path }}
        run: |
          xcodebuild build-for-testing -target 'KometUITests' -scheme Komet -configuration Release -derivedDataPath build CODE_SIGN_IDENTITY="-"
      - name: Build Debug
        env:
          DEVELOPER_DIR: ${{ matrix.xcode-path }}
        run: |
          xcodebuild build-for-testing -target 'KometUITests' -scheme Komet -configuration Debug -derivedDataPath build
      - name: Test Debug
        env:
          DEVELOPER_DIR: ${{ matrix.xcode-path }}
        run: |
          xcodebuild test-without-building -target 'KometUITests' -scheme Komet -configuration Debug -derivedDataPath build
      - name: Archive Test Results
        if: failure()
        uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.upload-name }}
          path: build/Logs
