name: XCUI Testing

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    strategy:
      matrix:
        xcode: ['xcode13.2.1']
        include:
            - xcode: 'xcode13.2.1'
              xcode-path: '/Applications/Xcode_13.2.1.app/Contents/Developer'
    
    name: Build and Test Komet on macOS
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build
        env:
          DEVELOPER_DIR: ${{ matrix.xcode-path }}
          CODE_SIGN_IDENTITY: '-'
        run: |
          xcodebuild build-for-testing -target 'KometUITests' -scheme Komet -configuration Release -derivedDataPath build
      - name: Test
        env:
          DEVELOPER_DIR: ${{ matrix.xcode-path }}
          CODE_SIGN_IDENTITY: '-'
        run: |
          xcodebuild test-without-building -target 'KometUITests' -scheme Komet -configuration Release -derivedDataPath build
      - name: Archive Test Results
        if: failure()
        uses: actions/upload-artifact@v2
        with:
          name: build-logs
          path: build/Logs
