name: XCUI Testing

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Build and Test Komet on macOS
    runs-on: macos-11

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build
        env:
          CODE_SIGN_IDENTITY: -
        run: |
          xcodebuild build-for-testing -target 'KometUITests' -scheme Komet -configuration Release -derivedDataPath build
      - name: Test
        env:
          CODE_SIGN_IDENTITY: -
        run: |
          xcodebuild test-without-building -target 'KometUITests' -scheme Komet -configuration Release -derivedDataPath build
      - name: Archive Test Results
        if: failure()
        uses: actions/upload-artifact@v2
        with:
          name: build-logs
          path: build/Logs
